AWSTemplateFormatVersion: 2010-09-09
Description: |
  CloudFormation Template for Roman Numerals Converter Application.
  This template creates Python Flask Web Application on Amazon Linux 2 AMI
  (latest ami) EC2 Instance with custom security group
  allowing http connections on port 80 and SSH connection on port 22.
  Roman Numerals Converter Application is downloaded from Github
  repository, then installed on Flask.
Parameters:
 parameter ParameterName:
   Description: enter your keypair
   Type: AWS::EC2::KeyPair::KeyName

  
  
Resources:
  
Outputs: